networks:
  app-tier:
    driver: bridge
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: tw-api
    ports:
      - 8080:8080
    networks:
      - app-tier