@host = localhost:8080


### Store the reading meter with smartMeterId
POST http://{{host}}/readings/store
Content-Type: application/json

{
    "smartMeterId": "taae",
    "electricityReadings": [
        {
            "time": "2024-05-01T04:08:16.687078474Z",
            "reading": 1.1678
        },
        {
            "time": "2024-05-01T04:08:26.687078474Z",
            "reading": 1.2489
        },
        {
            "time": "2024-05-01T04:08:36.687078474Z",
            "reading": 0.1613
        }
    ]
}


### Read by smartMeterId
GET http://{{host}}/readings/read/taae
Content-Type: application/json


### Compare ALL 
GET http://{{host}}/price-plans/compare-all/taae
Content-Type: application/json


### Recommend
GET http://{{host}}/price-plans/recommend/taae?limit=3
Content-Type: application/json