@host = localhost:8080


### Store the reading meter with smartMeterId
POST http://{{host}}/readings/store
Content-Type: application/json

{
    "smartMeterId": "taae",
    "electricityReadings": [
        {
            "time": "2024-04-28T04:08:16.687078474Z",
            "reading": 200
        },
        {
            "time": "2024-04-29T04:08:36.687078474Z",
            "reading": 100
        },
        {
            "time": "2024-04-30T04:08:36.687078474Z",
            "reading": 100
        }
    ]
}


### Store the reading meter with smartMeterId
POST http://{{host}}/price-plans/power-user-cost
Content-Type: application/json

{
    "day": 7,
    "smartMeterId": "taae"
}

### Read by smartMeterId
GET http://{{host}}/readings/read/taae?day=7
Content-Type: application/json


### Compare ALL 
GET http://{{host}}/price-plans/compare-all/taae
Content-Type: application/json


### Recommend
GET http://{{host}}/price-plans/recommend/taae?limit=3
Content-Type: application/json